### ISSUE TITLE
Both source_gen:combining_builder and mix_generator may output. Potential outputs must be unique across all builders.

### ISSUE THREAD

**Issue by definev** [btwld/mix#614]
### Flutter version

Both source_gen:combining_builder and mix_generator may output lib/configurations/di_initialize.g.dart. Potential outputs must be unique across all builders. See https://github.com/dart-lang/build/blob/master/docs/faq.md#why-do-builders-need-unique-outputs

### Steps to reproduce

Using two different code gen package that use the same `.g.dart` output file.

### Expected results

Generate file successfully

### Actual results

Conflicting therefore i can't using mix generator

### Code sample

<details open><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>

**Comment by definev** [comment]
@leoafarias hello, this bug is prevent us from using mix in pub.dev, the workaround it is manually change the `.g.dart` generated file to `.mix.dart` in `mix_generator`. But that very annoying

**Comment by skyegallup** [comment]
This might be a duplicate of #561 ?

@definev If it's helpful, I was able to work around the issue by updating my project's `build.yaml`:
```yaml
# assuming all widgets using `mix_generator` are in `lib/widgets/`:
targets:
  $default:
    builders:
      mix_generator:
        generate_for:
          include:
            - lib/widgets/*.dart
            - lib/widgets/**/*.dart
      source_gen:combining_builder:
        generate_for:
          exclude:
            - lib/widgets/*.dart
            - lib/widgets/**/*.dart
```

This keeps the two builders from trying to generate `*.g.dart` files for the same source files. However, it'd be simpler if `mix_generator` were updated to play nicer with `source_gen` better, or at least to use a different file extension instead of `.g.dart`.
